import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MyNavigation from "@/components/(layout comps)/MyNavigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-6xl relative mx-auto ">
          <MyNavigation />
          <div className="pt-52">{children}</div>
        </div>
      </body>
    </html>
  );
}
