import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/(providers)/theme-provider";
import MyNavigation from "@/components/(layout comps)/MyNavigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="max-w-2xl relative mx-auto ">
            <MyNavigation />
            <div className="pt-32 px-5 md:px-0">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
