import MyLogo from "@/components/(brand)/MyLogo";
import ScrollToTop from "@/components/(providers)/ScrollToTop";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "BounaderMedRafik | Blogs",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <div>
        <MyLogo />
      </div>
      <div className="pb-52">
        {children} <ScrollToTop />
      </div>
    </div>
  );
}
